version: '3.8'
services:
  tz-golang:
    container_name: tz-golang
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      TIME_ZONE: "Asia/Tokyo"